# Generated by Django 2.1.7 on 2019-06-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0002_customuser_contributions")]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="amount_comments",
            field=models.IntegerField(default="0"),
        )
    ]
