# Generated by Django 2.1.7 on 2019-05-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blog", "0002_blog_image")]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to=""),
        )
    ]
