# Generated by Django 2.1.7 on 2019-08-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default='2001-01-01'),
        ),
        migrations.AlterField(
            model_name='blog_comment',
            name='text',
            field=models.TextField(verbose_name='Comment text'),
        ),
    ]
