# Generated by Django 2.2.3 on 2019-08-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blog", "0006_auto_20190803_0947")]

    operations = [
        migrations.AlterField(
            model_name="blog", name="pub_date", field=models.DateTimeField()
        )
    ]
