# Generated by Django 2.1.7 on 2019-08-10 11:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20190810_0824'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_comment',
            new_name='BlogComment',
        ),
    ]
