# Generated by Django 2.1.7 on 2019-04-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ticket", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                ("text", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="ticket",
            name="progress",
            field=models.CharField(
                choices=[("To do", "To do"),
                         ("Doing", "Doing"), ("Done", "Done")],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="ticket_type",
            field=models.CharField(
                choices=[("Bug", "Bug"), ("Feature", "Feature")],
                default="1",
                max_length=10,
            ),
        ),
    ]
