# Generated by Django 2.1.7 on 2019-05-20 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0005_auto_20190520_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='author',
            field=models.ForeignKey(default='1',
                                    on_delete=django.db.models.
                                    deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
