# Generated by Django 2.1.7 on 2019-05-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ticket", "0006_ticket_author")]

    operations = [
        migrations.AddField(
            model_name="ticket", name="upvotes", field=models.IntegerField(default="0")
        )
    ]
