# Generated by Django 2.1.7 on 2019-07-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ticket", "0007_ticket_upvotes")]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="pub_date",
            field=models.DateTimeField(default="2001-01-01"),
        )
    ]
