# Generated by Django 2.1.7 on 2019-05-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_ticket_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pub_date',
            field=models.DateTimeField(default='2001-01-01'),
        ),
    ]
