# Generated by Django 2.1.7 on 2019-05-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_auto_20190525_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
